name = "easytorbox-referrals-api"
main = "src/index.js"
compatibility_date = "2026-05-16"

[[d1_databases]]
binding = "DB"
database_name = "torbox-referrals-prod"
database_id = "99db8ea3-bf26-4685-9e9b-e15f578a081d"
